#!/usr/bin/env bash
#
# release/build-client.sh — build the fb-idb Python client wheel.
#
#   stdout: absolute path to the produced .whl (machine-readable).
#   stderr: human-facing logs.
#
# Reuses setup.py's existing proto-gen path: its BuildPyCommand runs
# grpc_tools.protoc with the repo's protoc-gen-python_grpc plugin and fixes the
# import paths. We do NOT hand-edit generated stubs. There is no pyproject.toml,
# so we build with --no-isolation inside a venv that already has the backend plus
# the exact build deps the generator needs.
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=release/version.sh
. "$SELF_DIR/version.sh"

log() { printf '[build-client] %s\n' "$*" >&2; }
die() { printf '[build-client] error: %s\n' "$*" >&2; exit 1; }

cd "$NB_REPO_ROOT"

# setup.py's BuildPyCommand writes a generated `protoc-gen-python_grpc` wrapper
# (and an egg-info) into the repo root. Remove them on exit so the working tree
# stays clean — release.sh refuses to release from a dirty tree.
cleanup() {
  rm -rf "${VERIFY_VENV:-/nonexistent}" 2>/dev/null || true
  rm -f "$NB_REPO_ROOT/protoc-gen-python_grpc" 2>/dev/null || true
  rm -rf "$NB_REPO_ROOT/fb_idb.egg-info" 2>/dev/null || true
}
trap cleanup EXIT

# Keep stdout clean for the caller: this script's ONLY real-stdout output is the
# final wheel path (release.sh captures it). Route pip/build chatter to stderr;
# fd 3 carries the path.
exec 3>&1 1>&2

# python@3.12 specifically: the client calls asyncio.get_event_loop(), removed in 3.13+.
PYTHON="${NB_PYTHON:-python3.12}"
command -v "$PYTHON" >/dev/null 2>&1 || die "missing $PYTHON — see release/RELEASING.md (H6)"

BUILD_VENV="$NB_REPO_ROOT/Build/client-build-venv"
log "build venv: $BUILD_VENV ($("$PYTHON" --version 2>&1))"
rm -rf "$BUILD_VENV"
"$PYTHON" -m venv "$BUILD_VENV"
VPY="$BUILD_VENV/bin/python"

# Build backend + the build-time deps setup.py's BuildPyCommand needs.
#  - grpclib==0.4.1 exactly: protoc_compiler_template.py hard-pins it via
#    load_entry_point, so the generator raises against any other version.
#  - setuptools<81: that plugin also does `from pkg_resources import
#    load_entry_point`, but setuptools>=81 removed the bundled pkg_resources.
#    Pin to a release that still ships it. (Upstream tech debt — the plugin
#    should target importlib.metadata.)
"$VPY" -m pip install --quiet --upgrade pip
"$VPY" -m pip install --quiet build "setuptools<81" wheel grpcio-tools "grpclib==0.4.1"

mkdir -p "$NB_ARTIFACTS_DIR"
rm -f "$NB_ARTIFACTS_DIR"/fb_idb-*.whl   # keep the glob below unambiguous across re-runs

log "building wheel $FB_IDB_VERSION (proto stubs regenerated by setup.py)"
# FB_IDB_VERSION drives the package version (setup.py requires it). --no-isolation
# so the generator sees the deps installed above (a default isolated build env
# would lack grpcio-tools/grpclib since there's no pyproject build-system table).
FB_IDB_VERSION="$FB_IDB_VERSION" \
  "$VPY" -m build --wheel --no-isolation --outdir "$NB_ARTIFACTS_DIR" "$NB_REPO_ROOT"

# wheel escapes '+' to '_' in the filename, so glob rather than predict the name.
WHEEL="$(ls -t "$NB_ARTIFACTS_DIR"/fb_idb-*.whl 2>/dev/null | head -1 || true)"
[[ -n "$WHEEL" && -f "$WHEEL" ]] || die "wheel not produced in $NB_ARTIFACTS_DIR"

# --- Acceptance (A3) ------------------------------------------------------
# Install into a CLEAN py3.12 venv; confirm the `idb` console script exists and
# exposes the new pinch command.
if [[ "${NB_SKIP_VERIFY:-0}" != "1" ]]; then
  VERIFY_VENV="$(mktemp -d "${TMPDIR:-/tmp}/nb-client-verify.XXXXXX")"  # removed by cleanup() on EXIT
  log "verifying wheel in a clean venv"
  "$PYTHON" -m venv "$VERIFY_VENV"
  "$VERIFY_VENV/bin/pip" install --quiet "$WHEEL"
  "$VERIFY_VENV/bin/idb" ui pinch --help >/dev/null \
    || die "installed wheel lacks 'idb ui pinch' (gesture work missing from this commit?)"
  log "verify OK — installed fb-idb $("$VERIFY_VENV/bin/pip" show fb-idb | awk '/^Version:/{print $2}'); 'idb ui pinch' present"
fi

log "done: $WHEEL"
printf '%s\n' "$WHEEL" >&3
